let book1=document.getElementById("mb1")
let summary1=document.getElementById("msummary1")
let show1=document.getElementById("mshow1")
let hide1=document.getElementById("mhide1")

let book2=document.getElementById("mb2")
let summary2=document.getElementById("msummary2")
let show2=document.getElementById("mshow2")
let hide2=document.getElementById("mhide2")

let book3=document.getElementById("mb3")
let summary3=document.getElementById("msummary3")
let show3=document.getElementById("mshow3")
let hide3=document.getElementById("mhide3")

let book4=document.getElementById("mb4")
let summary4=document.getElementById("msummary4")
let show4=document.getElementById("mshow4")
let hide4=document.getElementById("mhide4")

let book5=document.getElementById("mb5")
let summary5=document.getElementById("msummary5")
let show5=document.getElementById("mshow5")
let hide5=document.getElementById("mhide5")

let book6=document.getElementById("mb6")
let summary6=document.getElementById("msummary6")
let show6=document.getElementById("mshow6")
let hide6=document.getElementById("mhide6")
show1.onclick=function(){
    book1.style.display="none"
    book2.style.display="none"
    book3.style.display="none"
    book4.style.display="none"
    book5.style.display="none"
    book6.style.display="none"
    show1.style.display="none"
    show2.style.display="none"
    show3.style.display="none"
    show4.style.display="none" 
    show5.style.display="none"
    show6.style.display="none" 
    summary2.style.display="none"
    summary3.style.display="none"
    summary4.style.display="none"
    summary5.style.display="none"
    summary6.style.display="none"
    hide2.style.display="none"
    hide3.style.display="none"
    hide4.style.display="none"
    hide5.style.display="none"
    hide6.style.display="none"
    hide1.style.display="block"
    summary1.style.display="block"
}
hide1.onclick=function(){
    book1.style.display="block"
    book2.style.display="block"
    book3.style.display="block"
    book4.style.display="block"
    book5.style.display="block"
    book6.style.display="block"
    show1.style.display="block"
    show2.style.display="block"
    show3.style.display="block"
    show4.style.display="block" 
    show5.style.display="block"
    show6.style.display="block" 
    hide1.style.display="none"
    summary1.style.display="none"
}

show2.onclick=function(){
    book1.style.display="none"
    book2.style.display="none"
    book3.style.display="none"
    book4.style.display="none"
    book5.style.display="none"
    book6.style.display="none"
    show1.style.display="none"
    show2.style.display="none"
    show3.style.display="none"
    show4.style.display="none" 
    show5.style.display="none"
    show6.style.display="none" 
    summary1.style.display="none"
    summary3.style.display="none"
    summary4.style.display="none"
    summary5.style.display="none"
    summary6.style.display="none"
    hide1.style.display="none"
    hide3.style.display="none"
    hide4.style.display="none"
    hide5.style.display="none"
    hide6.style.display="none"
    hide2.style.display="block"
    summary2.style.display="block"
}

hide2.onclick=function(){
    book1.style.display="block"
    book2.style.display="block"
    book3.style.display="block"
    book4.style.display="block"
    book5.style.display="block"
    book6.style.display="block"
    show1.style.display="block"
    show2.style.display="block"
    show3.style.display="block"
    show4.style.display="block" 
    show5.style.display="block"
    show6.style.display="block" 
    hide2.style.display="none"
    summary2.style.display="none"
}

show3.onclick=function(){
    book1.style.display="none"
    book2.style.display="none"
    book3.style.display="none"
    book4.style.display="none"
    book5.style.display="none"
    book6.style.display="none"
    show1.style.display="none"
    show2.style.display="none"
    show3.style.display="none"
    show4.style.display="none" 
    show5.style.display="none"
    show6.style.display="none" 
    summary1.style.display="none"
    summary2.style.display="none"
    summary4.style.display="none"
    summary5.style.display="none"
    summary6.style.display="none"
    hide1.style.display="none"
    hide2.style.display="none"
    hide4.style.display="none"
    hide5.style.display="none"
    hide6.style.display="none"
    hide3.style.display="block"
    summary3.style.display="block"
}
hide3.onclick=function(){
    book1.style.display="block"
    book2.style.display="block"
    book3.style.display="block"
    book4.style.display="block"
    book5.style.display="block"
    book6.style.display="block"
    show1.style.display="block"
    show2.style.display="block"
    show3.style.display="block"
    show4.style.display="block" 
    show5.style.display="block"
    show6.style.display="block" 
    hide3.style.display="none"
    summary3.style.display="none"
}

show4.onclick=function(){
    book1.style.display="none"
    book2.style.display="none"
    book3.style.display="none"
    book4.style.display="none"
    book5.style.display="none"
    book6.style.display="none"
    show1.style.display="none"
    show2.style.display="none"
    show3.style.display="none"
    show4.style.display="none" 
    show5.style.display="none"
    show6.style.display="none" 
    summary1.style.display="none"
    summary2.style.display="none"
    summary3.style.display="none"
    summary5.style.display="none"
    summary6.style.display="none"
    hide1.style.display="none"
    hide2.style.display="none"
    hide4.style.display="none"
    hide5.style.display="none"
    hide6.style.display="none"
    hide4.style.display="block"
    summary4.style.display="block"
}
hide4.onclick=function(){
    book1.style.display="block"
    book2.style.display="block"
    book3.style.display="block"
    book4.style.display="block"
    book5.style.display="block"
    book6.style.display="block"
    show1.style.display="block"
    show2.style.display="block"
    show3.style.display="block"
    show4.style.display="block" 
    show5.style.display="block"
    show6.style.display="block" 
    hide4.style.display="none"
    summary4.style.display="none"
}

show5.onclick=function(){
    book1.style.display="none"
    book2.style.display="none"
    book3.style.display="none"
    book4.style.display="none"
    book5.style.display="none"
    book6.style.display="none"
    show1.style.display="none"
    show2.style.display="none"
    show3.style.display="none"
    show4.style.display="none" 
    show5.style.display="none"
    show6.style.display="none" 
    summary1.style.display="none"
    summary2.style.display="none"
    summary3.style.display="none"
    summary4.style.display="none"
    summary6.style.display="none"
    hide1.style.display="none"
    hide2.style.display="none"
    hide4.style.display="none"
    hide3.style.display="none"
    hide6.style.display="none"
    hide5.style.display="block"
    summary5.style.display="block"
}
hide5.onclick=function(){
    book1.style.display="block"
    book2.style.display="block"
    book3.style.display="block"
    book4.style.display="block"
    book5.style.display="block"
    book6.style.display="block"
    show1.style.display="block"
    show2.style.display="block"
    show3.style.display="block"
    show4.style.display="block" 
    show5.style.display="block"
    show6.style.display="block" 
    hide5.style.display="none"
    summary5.style.display="none"
}

show6.onclick=function(){
    book1.style.display="none"
    book2.style.display="none"
    book3.style.display="none"
    book4.style.display="none"
    book5.style.display="none"
    book6.style.display="none"
    show1.style.display="none"
    show2.style.display="none"
    show3.style.display="none"
    show4.style.display="none" 
    show5.style.display="none"
    show6.style.display="none" 
    summary1.style.display="none"
    summary2.style.display="none"
    summary3.style.display="none"
    summary4.style.display="none"
    summary5.style.display="none"
    hide1.style.display="none"
    hide2.style.display="none"
    hide4.style.display="none"
    hide3.style.display="none"
    hide5.style.display="none"
    hide6.style.display="block"
    summary6.style.display="block"
}
hide6.onclick=function(){
    book1.style.display="block"
    book2.style.display="block"
    book3.style.display="block"
    book4.style.display="block"
    book5.style.display="block"
    book6.style.display="block"
    show1.style.display="block"
    show2.style.display="block"
    show3.style.display="block"
    show4.style.display="block" 
    show5.style.display="block"
    show6.style.display="block" 
    hide6.style.display="none"
    summary6.style.display="none"
}



